//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_version.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Delivering
    {
        public int Product_id { get; set; }
        [Required]
        public string Comodity { get; set; }
        public Nullable<int> Quantity { get; set; }
        [Display(Name = "Supplier Name")]
        public string SupplierName { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        [Display(Name = "Delivering By")]
        public string DeleveringBy { get; set; }
        [Required]
        public string Status { get; set; }
        [Display(Name = "Buying Price")]
        public Nullable<int> BuyingPrice { get; set; }
        [Display(Name = "Selling Price")]
        public Nullable<int> SellingPrice { get; set; }
    }
}
